### ISSUE TITLE
Question - is it possible to use init directive, configure mermaid?

### ISSUE THREAD

**Issue by tmuras** [SemanticMediaWiki/Mermaid#105]
Is it possible to use init directive, e.g.:
`%%{ init: { 'flowchart': { 'curve': 'stepAfter', "defaultRenderer": "dagre" } } }%%`

or frontmatter configuration, e.g.:
```
---
title: Hello Title
config:
  theme: base
  themeVariables:
    primaryColor: "#00ff00"
---
```
